---
- hosts: mediaserver_builder

  pre_tasks:
    - name: Ensure pacman cache is updated
      become: yes
      pacman:
        update_cache: yes

  roles:
    - role: jahrik.yay
      install: true
      aur_packages:
        - sonarr
        - radarr
        - prowlarr
        - overseerr
        - flaresolverr-bin

- hosts: mediaserver
  gather_facts: yes
  become: yes

  vars_files:
    - vars/main.yaml
    - vars/secrets.yaml

  handlers:
    - name: Restart nzbget
      systemd:
        name: nzbget
        daemon_reload: yes
        state: restarted

    - name: Restart qbittorrent
      systemd:
        name: qbittorrent-nox
        daemon_reload: yes
        state: restarted

  pre_tasks:
    - name: Ensure pacman cache is updated
      pacman:
        update_cache: yes

    - name: Ensure dependencies are installed
      pacman:
        name:
          - curl
          - sqlite3
          - rpcbind
          - nfs-utils
          - ntp
          - wireguard-tools
          - qbittorrent-nox
        state: present

    - name: Ensure ntpd daemon is started and enabled
      systemd:
        name: ntpd
        enabled: yes
        state: started

    - name: Ensure radarr daemon is started and enabled
      systemd:
        name: radarr
        enabled: yes
        state: started

    - name: Ensure sonarr daemon is started and enabled
      systemd:
        name: sonarr
        enabled: yes
        state: started

    - name: Ensure prowlarr daemon is started and enabled
      systemd:
        name: prowlarr
        enabled: yes
        state: started

    - name: Ensure overseerr daemon is started and enabled
      systemd:
        name: overseerr
        enabled: yes
        state: started

    - name: Ensure flaresolverr daemon is started and enabled
      systemd:
        name: flaresolverr
        enabled: yes
        state: started

    - name: Ensure that the media mount directory exists
      file:
        state: directory
        path: /mnt/media

    - name: Ensure that the media NFS is mounted
      mount:
        src: 192.168.4.245:/volume1/k8s/media-server/plex/data
        path: /mnt/media
        opts: rw,sync,hard,nfsvers=4.1
        state: mounted
        fstype: nfs

  tasks:
    - name: Ensure wireguard config is present
      copy:
        content: "{{ wireguard_config }}"
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600

    - name: Ensure that ip forwarding is enabled
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: yes
        reload: yes

    - name: Ensure wireguard interface is started and enabled
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started

    - name: Ensure that the media group exists
      group:
        name: media
        state: present

    - name: Ensure that the nzbget user exists
      user:
        append: yes
        groups:
          - media
        name: nzbget
        state: present

    - name: Ensure that the nzbget install file exists
      get_url:
        url: https://nzbget.net/download/nzbget-latest-bin-linux.run
        dest: /opt/install-nzbget.run

    - name: Ensure nzbget is installed
      become: yes
      become_user: nzbget
      command:
        cmd: sh /opt/install-nzbget.run
        chdir: /home/nzbget
        creates: /home/nzbget/nzbget/nzbget

    - name: Ensure the nzbget service file exists
      copy:
        src: config/nzbget.service
        dest: /etc/systemd/system/nzbget.service
        group: root
        owner: root
      notify:
        - Restart nzbget

    - name: Ensure the nzbget service is started and enabled
      systemd:
        name: nzbget
        daemon_reload: yes
        state: started

    - name: Ensure that the qbittorrent user exists
      user:
        append: yes
        groups:
          - media
        name: qbittorrent
        state: present

    - name: Ensure the qbittorrent service file exists
      copy:
        src: config/qbittorrent-nox.service
        dest: /etc/systemd/system/qbittorrent-nox.service
        group: root
        owner: root
      notify:
        - Restart qbittorrent

    - name: Ensure the qbittorret service is started and enabled
      systemd:
        name: qbittorrent-nox
        daemon_reload: yes
        state: started
