---
- hosts: portainer
  become: yes

  vars_files:
    - vars/main.yaml

  pre_tasks:
    - name: Ensure dependencies are installed
      pacman:
        update_cache: yes
        name:
          - ntp
          - docker

    - name: Ensure ntpd daemon is started and enabled
      systemd:
        name: ntpd
        enabled: yes
        state: started

    - name: Ensure docker daemon is started and enabled
      systemd:
        name: docker
        enabled: yes
        state: started

- hosts: portainer02
  become: yes

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Ensure portainer agent script is downloaded
      get_url:
        url: https://downloads.portainer.io/agent-stack-ce29.yml
        dest: /opt/agent-stack.yaml
        checksum: sha256:074f31f2d6c7aceae9a6f550a8993c77350be43c59e7e3e352b0ea953b4622b3

    - name: Ensure portainer agent stack is running
      command:
        cmd: >
          docker run -d
          -v /var/run/docker.sock:/var/run/docker.sock
          -v /var/lib/docker/volumes:/var/lib/docker/volumes
          -v /:/host
          -v portainer_agent_data:/data
          --restart always
          -e EDGE=1
          -e EDGE_ID=24bea4f7-44f4-4a48-b0e4-78a13f2fef6c
          -e EDGE_KEY=aHR0cHM6Ly8xOTIuMTY4LjUuMTU6OTQ0M3wxOTIuMTY4LjUuMTU6ODAwMHxhYzo0YzpkNDozYTowZjo0Yzo1NTo2MTo3MDozNzpkOTplODoyMDo4NzozMDpmMXwz
          -e CAP_HOST_MANAGEMENT=1
          -e EDGE_INSECURE_POLL=1
          --name portainer_edge_agent
          portainer/agent:2.9.3

- hosts: portainer03
  become: yes

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Ensure portainer agent script is downloaded
      get_url:
        url: https://downloads.portainer.io/agent-stack-ce29.yml
        dest: /opt/agent-stack.yaml
        checksum: sha256:074f31f2d6c7aceae9a6f550a8993c77350be43c59e7e3e352b0ea953b4622b3

    - name: Ensure portainer agent stack is running
      command:
        cmd: >
          docker run -d
          -v /var/run/docker.sock:/var/run/docker.sock
          -v /var/lib/docker/volumes:/var/lib/docker/volumes
          -v /:/host
          -v portainer_agent_data:/data
          --restart always
          -e EDGE=1
          -e EDGE_ID=24bea4f7-44f4-4a48-b0e4-78a13f2fef6c
          -e EDGE_KEY=aHR0cHM6Ly8xOTIuMTY4LjUuMTU6OTQ0M3wxOTIuMTY4LjUuMTU6ODAwMHxhYzo0YzpkNDozYTowZjo0Yzo1NTo2MTo3MDozNzpkOTplODoyMDo4NzozMDpmMXwz
          -e CAP_HOST_MANAGEMENT=1
          -e EDGE_INSECURE_POLL=1
          --name portainer_edge_agent
          portainer/agent:2.9.3

