---
- hosts: portainer
  become: yes

  vars_files:
    - vars/main.yaml

  pre_tasks:
    - name: Ensure dependencies are installed
      pacman:
        update_cache: yes
        name:
          - ntp
          - docker

    - name: Ensure ntpd daemon is started and enabled
      systemd:
        name: ntpd
        enabled: yes
        state: started

    - name: Ensure docker daemon is started and enabled
      systemd:
        name: docker
        enabled: yes
        state: started

  tasks:
    - name: Ensure portainer user is created
      user:
        name: portainer

    - name: Ensure that the portainer volumes directory is created
      file:
        path: /home/portainer/volumes
        state: directory

