---
- hosts: traefik
  gather_facts: yes
  become: yes

  vars_files:
    - vars/main.yaml
    - vars/secrets.yaml

  handlers:
    - name: Restart traefik
      systemd:
        name: traefik
        daemon_reload: yes
        state: restarted

  pre_tasks:
    - name: Ensure pacman cache is updated
      community.general.pacman:
        update_cache: yes

    - name: Ensure dependencies are installed
      pacman:
        name:
          - curl
          - ntp
        state: present

    - name: Ensure that ntpd is started and enabled
      service:
        name: ntpd
        enabled: true
        state: started

  tasks:
    - name: Ensure that cloudflared is downloaded
      get_url:
        url: "https://github.com/cloudflare/cloudflared/releases/download/{{ cloudflared_version }}/cloudflared-linux-amd64"
        dest: /usr/local/bin/cloudflared
        checksum: "{{ cloudflared_checksum }}"
    - name: Ensure that cloudflared is setup
      command:
        cmd: "cloudflared service install {{ cloudflared_key }}"
        creates: /etc/systemd/system/cloudflared.service

    - name: Ensure the cloudflared service is started and enabled
      systemd:
        name: cloudflared
        daemon_reload: yes
        enabled: true
        state: started

    - name: Ensure that the traefik group exists
      group:
        name: traefik
        state: present

    - name: Ensure that the traefik user exists
      user:
        append: yes
        groups:
          - traefik
        name: traefik
        state: present

    - name: Ensure that traefik is downloaded
      get_url:
        url: "https://github.com/traefik/traefik/releases/download/v{{ traefik_version }}/traefik_v{{ traefik_version }}_linux_amd64.tar.gz"
        dest: "/tmp/traefik-{{ traefik_version }}.tar.gz"
        checksum: "{{ traefik_checksum }}"

    - name: Ensure that traefik is extracted into the bin directory
      unarchive:
        remote_src: true
        src: "/tmp/traefik-{{ traefik_version }}.tar.gz"
        dest: /usr/local/bin/
        include:
          - traefik
        mode: 0755
        owner: root
        group: root

    - name: Ensure the traefik service file exists
      template:
        src: config/traefik.service.j2
        dest: /etc/systemd/system/traefik.service
        group: root
        owner: root
        mode: 0644
      notify:
        - Restart traefik

    - name: Ensure that the traefik config directory exists
      file:
        state: directory
        path: /etc/traefik
        owner: root
        group: root

    - name: Ensure that the traefik config acme directory exists
      file:
        state: directory
        path: /etc/traefik/acme
        owner: traefik
        group: traefik

    - name: Ensure that the traefik config conf directory exists
      file:
        state: directory
        path: /etc/traefik/conf
        owner: traefik
        group: traefik

    - name: Ensure the traefik static config file exists
      copy:
        src: config/traefik.static.yaml
        dest: /etc/traefik/traefik.yaml
        group: traefik
        owner: traefik
        mode: 0644
      notify:
        - Restart traefik

    - name: Ensure that the traefik dynamic config file exists
      copy:
        src: config/traefik.dynamic.yaml
        dest: /etc/traefik/conf/traefik.dynamic.yaml
        group: traefik
        owner: traefik
        mode : 0644

    - name: Ensure the traefik service is started and enabled
      systemd:
        name: traefik
        daemon_reload: yes
        enabled: true
        state: started
