http:
  routers:
    brennonloveless:
      entryPoints:
        - web
        - websecure
      rule: "Host(`brennonloveless.com`) || Host(`www.brennonloveless.com`)"
      tls:
        certResolver: "letsencrypt"

    overseerr:
      entryPoints:
        - web
      # middlewares:
      #   - redirect-to-https
      rule: "Host(`overseerr.brennonloveless.com`)"
      service: "kubernetes"

    overseerr-secure:
      entryPoints:
        - websecure
      rule: "Host(`overseerr.brennonloveless.com`)"
      service: "kubernetes-secure"
      tls:
        certResolver: "letsencrypt"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    kubernetes:
      loadBalancer:
        servers:
          - url: "http://192.168.4.225/"

    kubernetes-secure:
      loadBalancer:
        servers:
          - url: "http://192.168.4.225/"

