http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    brennonloveless:
      entryPoints:
        - web
      rule: "Host(`brennonloveless.com`) || Host(`www.brennonloveless.com`)"
      middlewares:
        - redirect-to-https
      service: noop@internal

    brennonloveless-secure:
      entryPoints:
        - websecure
      rule: "Host(`brennonloveless.com`) || Host(`www.brennonloveless.com`)"
      service: "brennonloveless"
      tls:
        certResolver: "letsencrypt"

    overseerr:
      entryPoints:
        - web
      rule: "Host(`overseerr.brennonloveless.com`)"
      middlewares:
        - redirect-to-https
      service: noop@internal

    overseerr-secure:
      entryPoints:
        - websecure
      rule: "Host(`overseerr.brennonloveless.com`)"
      service: "overseerr"
      tls:
        certResolver: "letsencrypt"

    dashboard:
      entryPoints:
        - web
      rule: "Host(`dashboard.lan`)"
      service: "dashboard"

    portainer:
      entryPoints:
        - web
      rule: "Host(`portainer.lan`)"
      middlewares:
        - redirect-to-https
      service: noop@internal

    portainer-secure:
      entryPoints:
        - websecure
      rule: "Host(`portainer.lan`)"
      service: "portainer"

    proxmox:
      entryPoints:
        - web
      rule: "Host(`proxmox.lan`)"
      middlewares:
        - redirect-to-https
      service: noop@internal

    proxmox-secure:
      entryPoints:
        - websecure
      rule: "Host(`proxmox.lan`)"
      service: "proxmox"

    nas:
      entryPoints:
        - web
      rule: "Host(`nas.lan`)"
      middlewares:
        - redirect-to-https
      service: noop@internal

    nas-secure:
      entryPoints:
        - websecure
      rule: "Host(`nas.lan`)"
      service: "nas"

    traefik:
      entryPoints:
        - web
      rule: "Host(`traefik.lan`)"
      service: "traefik"

    radarr:
      entryPoints:
        - web
      rule: "Host(`radarr.lan`)"
      service: "radarr"

    sonarr:
      entryPoints:
        - web
      rule: "Host(`sonarr.lan`)"
      service: "sonarr"

    prowlarr:
      entryPoints:
        - web
      rule: "Host(`prowlarr.lan`)"
      service: "prowlarr"

    nzbget:
      entryPoints:
        - web
      rule: "Host(`nzbget.lan`)"
      service: "nzbget"

    qbittorrent:
      entryPoints:
        - web
      rule: "Host(`qbittorrent.lan`)"
      service: "qbittorrent"

    fileflows:
      entryPoints:
        - web
      rule: "Host(`fileflows.lan`)"
      service: "fileflows"

  services:
    kubernetes:
      loadBalancer:
        servers:
          - url: "http://192.168.4.225/"

    brennonloveless:
      loadBalancer:
        servers:
          - url: "http://192.168.5.103/"

    dashboard:
      loadBalancer:
        servers:
          - url: "http://192.168.5.54:8080/"

    portainer:
      loadBalancer:
        servers:
          - url: "https://192.168.5.15:9443/"

    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.5.10:8006/"

    nas:
      loadBalancer:
        servers:
          - url: "https://192.168.4.245:5001/"

    traefik:
      loadBalancer:
        server:
          - url: "http://192.168.5.52:8080/"

    overseerr:
      loadBalancer:
        servers:
          - url: "http://192.168.5.13:5055/"

    radarr:
      loadBalancer:
        servers:
          - url: "http://192.168.5.13:7878/"

    sonarr:
      loadBalancer:
        servers:
          - url: "http://192.168.5.13:8989/"

    prowlarr:
      loadBalancer:
        servers:
          - url: "http://192.168.5.13:9696/"

    nzbget:
      loadBalancer:
        servers:
          - url: "http://192.168.5.13:6789/"

    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://192.168.5.13:8080/"

    fileflows:
      loadBalancer:
        servers:
          - url: "http://192.168.5.14:5000/"
