http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    brennonloveless:
      entryPoints:
        - web
      rule: "Host(`brennonloveless.com`) || Host(`www.brennonloveless.com`)"
      middlewares:
        - redirect-to-https
      service: noop@internal

    brennonloveless-secure:
      entryPoints:
        - websecure
      rule: "Host(`brennonloveless.com`) || Host(`www.brennonloveless.com`)"
      service: "brennonloveless"
      tls:
        certResolver: "letsencrypt"

    overseerr:
      entryPoints:
        - web
      rule: "Host(`overseerr.brennonloveless.com`)"
      middlewares:
        - redirect-to-https
      service: noop@internal

    overseerr-secure:
      entryPoints:
        - websecure
      rule: "Host(`overseerr.brennonloveless.com`)"
      service: "kubernetes"
      tls:
        certResolver: "letsencrypt"

    radarr:
      entryPoints:
        - web
      rule: "Host(`radarr.lan`) || Host(`www.radarr.lan`)"
      service: "radarr"

  services:
    kubernetes:
      loadBalancer:
        servers:
          - url: "http://192.168.4.225/"

    brennonloveless:
      loadBalancer:
        servers:
          - url: "http://192.168.5.103/"

    radarr:
      loadBalancer:
        servers:
          - url: "http://192.168.5.13:7878/"
