http:
  routers:
    brennonloveless:
      entryPoints:
        - websecure
      rule: "Host(`brennonloveless.com`) || Host(`www.brennonloveless.com`)"
      service: "brennonloveless"
      tls:
        certResolver: "letsencrypt"

    overseerr:
      entryPoints:
        - websecure
      rule: "Host(`overseerr.brennonloveless.com`)"
      service: "kubernetes"
      tls:
        certResolver: "letsencrypt"

  services:
    kubernetes:
      loadBalancer:
        servers:
          - url: "http://192.168.4.225/"

    brennonloveless:
      loadBalancer:
        servers:
          - url: "http://192.168.5.103/"

